CREATE DATABASE IF NOT EXISTS Pokeclone;
USE Pokeclone;

CREATE TABLE `pokemons` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `type1` varchar(255) DEFAULT NULL,
  `type2` varchar(255) DEFAULT NULL,
  `habitat` varchar(255) DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `stage` int DEFAULT NULL,
  `height` int DEFAULT NULL,
  `weight` decimal(10,2) DEFAULT NULL,
  `url_sprite` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=152 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `suggestions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nome` varchar(100) DEFAULT NULL,
  `matricula` varchar(20) DEFAULT NULL,
  `sugestao` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(1,'Bulbasaur','Relva','Veneno','Prados','Verde',1,70,6.90000000000000035,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(2,'Ivysaur','Relva','Veneno','Prados','Verde',2,100,13.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(3,'Venusaur','Relva','Veneno','Prados','Verde',3,200,100.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(4,'Charmander','Fogo','Não tens','Montanha','Vermelho',1,60,8.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(5,'Charmeleon','Fogo','Não tens','Montanha','Vermelho',2,110,19.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(6,'Charizard','Fogo','Voa','Montanha','Vermelho',3,170,90.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(7,'Squirtle','Água','Não tens','Borda de água','Azul',1,50,9.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(8,'Wartortle','Água','Não tens','Borda de água','Azul',2,100,22.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(9,'Blastoise','Água','Não tens','Borda de água','Azul',3,160,85.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(10,'Caterpie','Inseto','Não tens','Floresta','Verde',1,30,2.89999999999999991,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(11,'Metapod','Inseto','Não tens','Floresta','Verde',2,70,9.90000000000000035,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(12,'Butterfree','Inseto','Voa','Floresta','Roxo',3,110,32.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(13,'Weedle','Inseto','Veneno','Floresta','Castanho',1,30,3.20000000000000017,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(14,'Kakuna','Inseto','Veneno','Floresta','Amarelo',2,60,10.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(15,'Beedrill','Inseto','Veneno','Floresta','Amarelo',3,100,29.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(16,'Pidgey','Normal','Voa','Floresta','Castanho',1,30,1.80000000000000004,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(17,'Pidgeotto','Normal','Voa','Floresta','Castanho',2,110,30.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(18,'Pidgeot','Normal','Voa','Floresta','Castanho',3,150,39.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(19,'Rattata','Normal','Não tens','Prados','Roxo',1,30,3.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(20,'Raticate','Normal','Não tens','Prados','Castanho',2,70,18.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(21,'Spearow','Normal','Voa','Terreno acidentado','Castanho',1,30,2.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(22,'Fearow','Normal','Voa','Terreno acidentado','Castanho',2,120,38.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(23,'Ekans','Veneno','Não tens','Prados','Roxo',1,200,6.90000000000000035,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(24,'Arbok','Veneno','Não tens','Prados','Roxo',2,350,65.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(25,'Pikachu','Elétrico','Não tens','Floresta','Amarelo',1,40,6.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(26,'Raichu','Elétrico','Não tens','Floresta','Amarelo',2,80,30.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(27,'Sandshrew','Terra','Não tens','Terreno acidentado','Amarelo',1,60,12.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(28,'Sandslash','Terra','Não tens','Terreno acidentado','Amarelo',2,100,29.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(29,'Nidoran-f','Veneno','Não tens','Prados','Azul',1,40,7.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(30,'Nidorina','Veneno','Não tens','Prados','Azul',2,80,20.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(31,'Nidoqueen','Veneno','Terra','Prados','Azul',3,130,60.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(32,'Nidoran-m','Veneno','Não tens','Prados','Roxo',1,50,9.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(33,'Nidorino','Veneno','Não tens','Prados','Roxo',2,90,19.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(34,'Nidoking','Veneno','Terra','Prados','Roxo',3,140,62.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(35,'Clefairy','Normal','Não tens','Montanha','Rosa',1,60,7.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(36,'Clefable','Normal','Não tens','Montanha','Rosa',2,130,40.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(37,'Vulpix','Fogo','Não tens','Prados','Castanho',1,60,9.90000000000000035,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(38,'Ninetales','Fogo','Não tens','Prados','Amarelo',2,110,19.8999999999999985,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(39,'Jigglypuff','Normal','Não tens','Prados','Rosa',1,50,5.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(40,'Wigglytuff','Normal','Não tens','Prados','Rosa',2,100,12.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(41,'Zubat','Veneno','Voa','Caverna','Roxo',1,80,7.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(42,'Golbat','Veneno','Voa','Caverna','Roxo',2,160,55.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(43,'Oddish','Relva','Veneno','Prados','Azul',1,50,5.40000000000000035,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(44,'Gloom','Relva','Veneno','Prados','Azul',2,80,8.59999999999999964,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(45,'Vileplume','Relva','Veneno','Prados','Vermelho',3,120,18.6000000000000014,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(46,'Paras','Inseto','Relva','Floresta','Vermelho',1,30,5.40000000000000035,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(47,'Parasect','Inseto','Relva','Floresta','Vermelho',2,100,29.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(48,'Venonat','Inseto','Veneno','Floresta','Roxo',1,100,30.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(49,'Venomoth','Inseto','Veneno','Floresta','Roxo',2,150,12.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(50,'Diglett','Terra','Não tens','Caverna','Castanho',1,20,0.800000000000000044,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(51,'Dugtrio','Terra','Não tens','Caverna','Castanho',2,70,33.2999999999999971,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(52,'Meowth','Normal','Não tens','Urbano','Amarelo',1,40,4.20000000000000017,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(53,'Persian','Normal','Não tens','Urbano','Amarelo',2,100,32.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(54,'Psyduck','Água','Não tens','Borda de água','Amarelo',1,80,19.6000000000000014,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(55,'Golduck','Água','Não tens','Borda de água','Azul',2,170,76.5999999999999943,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(56,'Mankey','Luta','Não tens','Montanha','Castanho',1,50,28.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(57,'Primeape','Luta','Não tens','Montanha','Castanho',2,100,32.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(58,'Growlithe','Fogo','Não tens','Prados','Castanho',1,70,19.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(59,'Arcanine','Fogo','Não tens','Prados','Castanho',2,190,155.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(60,'Poliwag','Água','Não tens','Borda de água','Azul',1,60,12.4000000000000003,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(61,'Poliwhirl','Água','Não tens','Borda de água','Azul',2,100,20.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(62,'Poliwrath','Água','Luta','Borda de água','Azul',3,130,54.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(63,'Abra','Psíquico','Não tens','Urbano','Castanho',1,90,19.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(64,'Kadabra','Psíquico','Não tens','Urbano','Castanho',2,130,56.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(65,'Alakazam','Psíquico','Não tens','Urbano','Castanho',3,150,48.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(66,'Machop','Luta','Não tens','Montanha','Cinza',1,80,19.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(67,'Machoke','Luta','Não tens','Montanha','Cinza',2,150,70.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(68,'Machamp','Luta','Não tens','Montanha','Cinza',3,160,130.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(69,'Bellsprout','Relva','Veneno','Floresta','Verde',1,70,4.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(70,'Weepinbell','Relva','Veneno','Floresta','Verde',2,100,6.40000000000000035,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(71,'Victreebel','Relva','Veneno','Floresta','Verde',3,170,15.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(72,'Tentacool','Água','Veneno','Mar','Azul',1,90,45.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(73,'Tentacruel','Água','Veneno','Mar','Azul',2,160,55.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(74,'Geodude','Pedra','Terra','Montanha','Castanho',1,40,20.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(75,'Graveler','Pedra','Terra','Montanha','Castanho',2,100,105.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(76,'Golem','Pedra','Terra','Montanha','Castanho',3,140,300.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(77,'Ponyta','Fogo','Não tens','Prados','Amarelo',1,100,30.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(78,'Rapidash','Fogo','Não tens','Prados','Amarelo',2,170,95.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(79,'Slowpoke','Água','Psíquico','Borda de água','Rosa',1,120,36.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(80,'Slowbro','Água','Psíquico','Borda de água','Rosa',2,160,78.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(81,'Magnemite','Elétrico','Não tens','Terreno acidentado','Cinza',1,30,6.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(82,'Magneton','Elétrico','Não tens','Terreno acidentado','Cinza',2,100,60.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(83,'Farfetchd','Normal','Voa','Prados','Castanho',1,80,15.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(84,'Doduo','Normal','Voa','Prados','Castanho',1,140,39.2000000000000028,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(85,'Dodrio','Normal','Voa','Prados','Castanho',2,180,85.2000000000000028,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(86,'Seel','Água','Não tens','Mar','Branco',1,110,90.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(87,'Dewgong','Água','Gelo','Mar','Branco',2,170,120.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(88,'Grimer','Veneno','Não tens','Urbano','Roxo',1,90,30.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(89,'Muk','Veneno','Não tens','Urbano','Roxo',2,120,30.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(90,'Shellder','Água','Não tens','Mar','Roxo',1,30,4.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(91,'Cloyster','Água','Gelo','Mar','Roxo',2,150,132.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(92,'Gastly','Fantasma','Veneno','Caverna','Roxo',1,130,0.100000000000000005,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(93,'Haunter','Fantasma','Veneno','Caverna','Roxo',2,160,0.100000000000000005,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(94,'Gengar','Fantasma','Veneno','Caverna','Roxo',3,150,40.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(95,'Onix','Pedra','Terra','Caverna','Cinza',1,880,210.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(96,'Drowzee','Psíquico','Não tens','Prados','Amarelo',1,100,32.3999999999999985,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(97,'Hypno','Psíquico','Não tens','Prados','Amarelo',2,160,75.5999999999999943,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(98,'Krabby','Água','Não tens','Borda de água','Vermelho',1,40,6.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(99,'Kingler','Água','Não tens','Borda de água','Vermelho',2,130,60.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(100,'Voltorb','Elétrico','Não tens','Urbano','Vermelho',1,50,10.4000000000000003,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(101,'Electrode','Elétrico','Não tens','Urbano','Vermelho',2,120,66.5999999999999943,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(102,'Exeggcute','Relva','Psíquico','Floresta','Rosa',1,40,2.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(103,'Exeggutor','Relva','Psíquico','Floresta','Amarelo',2,200,120.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(104,'Cubone','Terra','Não tens','Montanha','Castanho',1,40,6.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(105,'Marowak','Terra','Não tens','Montanha','Castanho',2,100,45.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(106,'Hitmonlee','Luta','Não tens','Urbano','Castanho',1,150,49.7999999999999971,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(107,'Hitmonchan','Luta','Não tens','Urbano','Castanho',1,140,50.2000000000000028,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(108,'Lickitung','Normal','Não tens','Prados','Rosa',1,120,65.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(109,'Koffing','Veneno','Não tens','Urbano','Roxo',1,60,1.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(110,'Weezing','Veneno','Não tens','Urbano','Roxo',2,120,9.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(111,'Rhyhorn','Terra','Pedra','Terreno acidentado','Cinza',1,100,115.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(112,'Rhydon','Terra','Pedra','Terreno acidentado','Cinza',2,190,120.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(113,'Chansey','Normal','Não tens','Urbano','Rosa',1,110,34.6000000000000014,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(114,'Tangela','Relva','Não tens','Prados','Azul',1,100,35.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(115,'Kangaskhan','Normal','Não tens','Prados','Castanho',1,220,80.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(116,'Horsea','Água','Não tens','Mar','Azul',1,40,8.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(117,'Seadra','Água','Não tens','Mar','Azul',2,120,25.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(118,'Goldeen','Água','Não tens','Borda de água','Vermelho',1,60,15.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(119,'Seaking','Água','Não tens','Borda de água','Vermelho',2,130,39.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(120,'Staryu','Água','Não tens','Mar','Castanho',1,80,34.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(121,'Starmie','Água','Psíquico','Mar','Roxo',2,110,80.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(122,'Mr.Mime','Psíquico','Não tens','Urbano','Rosa',1,130,54.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(123,'Scyther','Inseto','Voa','Prados','Verde',1,150,56.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(124,'Jynx','Gelo','Psíquico','Urbano','Vermelho',1,140,40.6000000000000014,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(125,'Electabuzz','Elétrico','Não tens','Prados','Amarelo',1,110,30.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(126,'Magmar','Fogo','Não tens','Montanha','Vermelho',1,130,44.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(127,'Pinsir','Inseto','Não tens','Floresta','Castanho',1,150,55.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(128,'Tauros','Normal','Não tens','Prados','Castanho',1,140,88.4000000000000056,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(129,'Magikarp','Água','Não tens','Borda de água','Vermelho',1,90,10.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(130,'Gyarados','Água','Voa','Borda de água','Azul',2,650,235.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(131,'Lapras','Água','Gelo','Mar','Azul',1,250,220.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(132,'Ditto','Normal','Não tens','Urbano','Roxo',1,30,4.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(133,'Eevee','Normal','Não tens','Urbano','Castanho',1,30,6.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(134,'Vaporeon','Água','Não tens','Urbano','Azul',2,100,29.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(135,'Jolteon','Elétrico','Não tens','Urbano','Amarelo',2,80,24.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(136,'Flareon','Fogo','Não tens','Urbano','Vermelho',2,90,25.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(137,'Porygon','Normal','Não tens','Urbano','Rosa',1,80,36.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(138,'Omanyte','Pedra','Água','Mar','Azul',1,40,7.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(139,'Omastar','Pedra','Água','Mar','Azul',2,100,35.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(140,'Kabuto','Pedra','Água','Mar','Castanho',1,50,11.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(141,'Kabutops','Pedra','Água','Mar','Castanho',2,130,40.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(142,'Aerodactyl','Pedra','Voa','Montanha','Roxo',1,180,59.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(143,'Snorlax','Normal','Não tens','Montanha','Azul',1,210,460.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(144,'Articuno','Gelo','Voa','Raro','Azul',1,170,55.3999999999999985,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(145,'Zapdos','Elétrico','Voa','Raro','Amarelo',1,160,52.6000000000000014,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(146,'Moltres','Fogo','Voa','Raro','Amarelo',1,200,60.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(147,'Dratini','Dragão','Não tens','Borda de água','Azul',1,180,3.29999999999999982,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(148,'Dragonair','Dragão','Não tens','Borda de água','Azul',2,400,16.5,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(149,'Dragonite','Dragão','Voa','Borda de água','Castanho',3,220,210.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(150,'Mewtwo','Psíquico','Não tens','Raro','Roxo',1,200,122.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png');
INSERT INTO pokemons(id,name,type1,type2,habitat,color,stage,height,weight,url_sprite) VALUES(151,'Mew','Psíquico','Não tens','Raro','Rosa',1,40,4.0,'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png');